name: Pipeline QA - Tests API

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  tests-automatises:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Récupération du code
      uses: actions/checkout@v4

    - name: 🐍 Installation de Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: 📦 Installation des dependances
      run: |
        python -m pip install --upgrade pip
        pip install Flask pytest requests

    - name: 🧪 Lancement des tests Pytest
      run: |
        pytest